[project]
name = "langrinder"
version = "1.0.0"
description = "Engine for I18N with telegrinder integraion"
authors = [
    {name = "tirch",email = "247108189-tirch@users.noreply.gitlab.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "telegrinder (>=0.4.2,<0.5.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "typer (>=0.16.0,<0.17.0)",
    "halo (>=0.0.31,<0.0.32)",
    "toml (>=0.10.2,<0.11.0)",
    "mako (>=1.3.10,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.12"
sphinx = "^8.2.3"

[tool.poetry.scripts]
langrinder = "langrinder.cli.cli:cli"

[tool.langrinder]
default_locale = "ru"
node = "langrinder.nodes.ConstLanguageCode"
locales_path = "examples/locales"
output = "examples/locales/i18n.py"
translation_name = "Translation"

[tool.ruff]
line-length = 79
target-version = "py312"
src = ["src"]

include = ["langrinder/**.py"]
exclude = []

[tool.ruff.lint]
select = [
    "ALL"
]
ignore = [
    "ARG",
    "ANN",
    "D",
    "EM101",
    "EM102",
    "PT001",
    "PT023",
    "SIM108",
    "RET505",
    "PLR0913",
    "SIM103",
    "ISC003",
    "SIM114", # identical by code != identical by meaning
    # awful things, never use.
    # It makes runtime work differently from typechecker
    "TC001",
    "TC002",
    "TC003",
    "TC006",
    "UP038", # only affects perfomance and brings nothing useful
    "F401",
    "RUF",
    "S702"
]

[tool.ruff.lint.isort]
no-lines-before = ["local-folder"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "parents"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
